export const API_URL = 'http://localhost:8000'

export const LOG_IN_PENDING = 'LOG_IN_PENDING'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'
export const LOG_OUT = 'LOG_OUT'

export const REGISTER_PENDING = 'REGISTER_PENDING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const ADD_SCHEDULE_PENDING = 'ADD_SCHEDULE_PENDING'
export const ADD_SCHEDULE_SUCCESS = 'ADD_SCHEDULE_SUCCESS'
export const ADD_SCHEDULE_FAILURE = 'ADD_SCHEDULE_FAILURE'

export const GET_SCHEDULE_PENDING = 'GET_SCHEDULE_PENDING'
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS'
export const GET_SCHEDULE_FAILURE = 'GET_SCHEDULE_FAILURE'

export const ADD_WORKER_PENDING = 'ADD_WORKER_PENDING'
export const ADD_WORKER_SUCCESS = 'ADD_WORKER_SUCCESS'
export const ADD_WORKER_FAILURE = 'ADD_WORKER_FAILURE'

export const EDIT_WORKER_PENDING = 'EDIT_WORKER_PENDING'
export const EDIT_WORKER_SUCCESS = 'EDIT_WORKER_SUCCESS'
export const EDIT_WORKER_FAILURE = 'EDIT_WORKER_FAILURE'

export const DELETE_WORKER_PENDING = 'DELETE_WORKER_PENDING'
export const DELETE_WORKER_SUCCESS = 'DELETE_WORKER_SUCCESS'
export const DELETE_WORKER_FAILURE = 'DELETE_WORKER_FAILURE'

export const ADD_SHIFT_PENDING = 'ADD_SHIFT_PENDING'
export const ADD_SHIFT_SUCCESS = 'ADD_SHIFT_SUCCESS'
export const ADD_SHIFT_FAILURE = 'ADD_SHIFT_FAILURE'

export const EDIT_SHIFT_PENDING = 'EDIT_SHIFT_PENDING'
export const EDIT_SHIFT_SUCCESS = 'EDIT_SHIFT_SUCCESS'
export const EDIT_SHIFT_FAILURE = 'EDIT_SHIFT_FAILURE'

export const DELETE_SHIFT_PENDING = 'DELETE_SHIFT_PENDING'
export const DELETE_SHIFT_SUCCESS = 'DELETE_SHIFT_SUCCESS'
export const DELETE_SHIFT_FAILURE = 'DELETE_SHIFT_FAILURE'
